# Generated by Django 2.2.11 on 2020-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='书名')),
            ],
            options={
                'verbose_name': 'books',
                'verbose_name_plural': 'books',
            },
        ),
    ]
